name: Ping

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:

  ping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ping my site
      - uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://yorkurobotics.com/
